### ISSUE TITLE
Sim. Disp. Std and Mean？

### ISSUE THREAD

**Issue by wuxiaofei01** [oakink/OakInk-Grasp-Generation#1]
![image](https://github.com/oakink/OakInk-Grasp-Generation/assets/61744147/4fa49c9e-fa3d-4e03-aef9-edece2424a4c)
Dear author, I would like to inquire about the presence of two components, namely **Sim. Disp. mean** and **Sim. Disp. std**, in the experimental section of the paper. However, upon reviewing the provided code, I noticed that only a **single return value exists**. Could you kindly clarify this discrepancy for me?
[Sim-Disp-std/mean](https://github.com/oakink/OakInk-Grasp-Generation/blob/main/lib/metrics/simulator.py)

**Comment by lixiny** [comment]
After calculating all Sim. Disp., you can use `np.mean(), np.std()` to get these values.

See: [evaluate_grasps](https://github.com/oakink/OakInk-Grasp-Generation/blob/72b10b6780ecc9c617a411775fdf5de56a9a18f7/scripts/evaluate_grasps.py#L152C47-L152C47)
